/// Complete Character Name to Enka Icon ID Mapping
/// Based on Enka.Network avatars.json
class CharacterIconMapper {
  static const Map<String, String> nameToIconId = {
    // Standard mappings
    'Kamisato Ayaka': 'Ayaka',
    'Jean': 'Qin',
    'Traveler': 'PlayerBoy',
    'Lisa': 'Lisa',
    'Barbara': 'Barbara',
    'Kaeya': 'Kaeya',
    'Diluc': 'Diluc',
    'Razor': 'Razor',
    'Amber': 'Ambor',
    'Venti': 'Venti',
    'Xiangling': 'Xiangling',
    'Beidou': 'Beidou',
    'Xingqiu': 'Xingqiu',
    'Xiao': 'Xiao',
    'Ningguang': 'Ningguang',
    'Klee': 'Klee',
    'Zhongli': 'Zhongli',
    'Fischl': 'Fischl',
    'Bennett': 'Bennett',
    'Tartaglia': 'Tartaglia',
    'Noelle': 'Noel',
    'Qiqi': 'Qiqi',
    'Chongyun': 'Chongyun',
    'Ganyu': 'Ganyu',
    'Albedo': 'Albedo',
    'Diona': 'Diona',
    'Mona': 'Mona',
    'Keqing': 'Keqing',
    'Sucrose': 'Sucrose',
    'Xinyan': 'Xinyan',
    'Rosaria': 'Rosaria',
    'Hu Tao': 'Hutao',
    'Kaedehara Kazuha': 'Kazuha',
    'Yanfei': 'Feiyan',
    'Yoimiya': 'Yoimiya',
    'Thoma': 'Tohma',
    'Eula': 'Eula',
    'Raiden Shogun': 'Shougun',
    'Sayu': 'Sayu',
    'Sangonomiya Kokomi': 'Kokomi',
    'Gorou': 'Gorou',
    'Kujou Sara': 'Sara',
    'Arataki Itto': 'Itto',
    'Yae Miko': 'Yae',
    'Shikanoin Heizou': 'Heizo',
    'Yelan': 'Yelan',
    'Kirara': 'Momoka',
    'Aloy': 'Aloy',
    'Shenhe': 'Shenhe',
    'Yun Jin': 'Yunjin',
    'Kuki Shinobu': 'Shinobu',
    'Kamisato Ayato': 'Ayato',
    'Collei': 'Collei',
    'Dori': 'Dori',
    'Tighnari': 'Tighnari',
    'Nilou': 'Nilou',
    'Cyno': 'Cyno',
    'Candace': 'Candace',
    'Nahida': 'Nahida',
    'Layla': 'Layla',
    'Wanderer': 'Wanderer',
    'Faruzan': 'Faruzan',
    'Yaoyao': 'Yaoyao',
    'Alhaitham': 'Alhatham',
    'Dehya': 'Dehya',
    'Mika': 'Mika',
    'Kaveh': 'Kaveh',
    'Baizhu': 'Baizhuer',
    'Lynette': 'Linette',
    'Lyney': 'Liney',
    'Freminet': 'Freminet',
    'Wriothesley': 'Wriothesley',
    'Neuvillette': 'Neuvillette',
    'Charlotte': 'Charlotte',
    'Furina': 'Furina',
    'Chevreuse': 'Chevreuse',
    'Navia': 'Navia',
    'Gaming': 'Gaming',
    'Xianyun': 'Liuyun',
    'Chiori': 'Chiori',
    'Sigewinne': 'Sigewinne',
    'Arlecchino': 'Arlecchino',
    'Sethos': 'Sethos',
    'Clorinde': 'Clorinde',
    'Emilie': 'Emilie',
    'Kachina': 'Kachina',
    'Kinich': 'Kinich',
    'Mualani': 'Mualani',
    'Xilonen': 'Xilonen',
    'Chasca': 'Chasca',
    'Ororon': 'Olorun',  // ← FIXED!
    'Mavuika': 'Mavuika',
    'Citlali': 'Citlali',
    'Lan Yan': 'Lanyan',
    'Yumemizuki Mizuki': 'Mizuki',
    'Iansan': 'Iansan',
    'Varesa': 'Varesa',
    'Escoffier': 'Escoffier',
    'Ifa': 'Ifa',
    'Skirk': 'SkirkNew',
    'Dahlia': 'Dahlia',
    'Ineffa': 'Ineffa',
    'Traveler (Aether)': 'PlayerBoy',
    'Traveler (Lumine)': 'PlayerGirl',
  };
  
  static String getIconId(String characterName) {
    return nameToIconId[characterName] ?? characterName.replaceAll(' ', '');
  }
}

